version: '3.7'
services:
  mysql:
    image: mariadb
    container_name: finance-app_db
    ports:
      - 3360:3306
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql:/var/lib/mysql

  phpmyadmin:
    container_name: finance-app_phpmyadmin
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    ports:
      - 2222:80
    networks:
      - default
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root

volumes:
  mysql:
    name: finance-app-db
