version: '3.3'

networks:
  default:
  web:
    external: true

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: finance-app_api
    restart: always

    env_file:
      - .env
    depends_on:
      - db
    environment:
      VIRTUAL_HOST: staging-api-app.citix.com.co
      VIRTUAL_PORT: 3000
      LETSENCRYPT_HOST: staging-api-app.citix.com.co
      LETSENCRYPT_EMAIL: principal@shf.com.co
    volumes:
      - ./:/app
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - web
      - default

  db:
    image: mariadb
    container_name: finance-app_db
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - finance-app-db:/var/lib/mysql
    env_file:
      - .env
  phpmyadmin:
    container_name: finance-app_phpmyadmin
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - 2222:80
    networks:
      - default
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root

volumes:
  finance-app-db:
