version: '3.7'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: finance-app_api
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - mysql
    env_file:
      - .env

  mysql:
    image: mariadb
    container_name: finance-app_db
    ports:
      - 3360:3306
    env_file:
      - .env
    volumes:
      - finance-app-db:/var/lib/mysql

  phpmyadmin:
    container_name: finance-app_phpmyadmin
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
    env_file:
      - .env

volumes:
  mysql:
    name: finance-app-db
