version: '3.7'
services:
  mysql:
    image: mariadb
    container_name: finance-app_db
    ports:
      - 3360:3306
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql:
    name: finance-app-db
